import { DetectedSubscription } from './subscriptionDetector';

// Demo subscriptions to showcase the app with all intelligence features
export const DEMO_SUBSCRIPTIONS: DetectedSubscription[] = [
  // Price increase + potential leak + hard to cancel
  {
    id: 'sub-netflix',
    name: 'Netflix',
    category: 'Entertainment',
    icon: '🎬',
    amount: 22.99,
    frequency: 'monthly',
    lastCharge: '2025-01-10',
    chargeCount: 18,
    status: 'active',
    transactions: [],
    priceChange: {
      previousAmount: 15.49,
      currentAmount: 22.99,
      changePercent: 48.4,
      changeDate: '2024-10-15',
    },
    priceHistory: [
      { date: '2023-07-15', amount: 13.99 },
      { date: '2024-01-15', amount: 15.49 },
      { date: '2024-10-15', amount: 22.99 },
    ],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation in account settings',
    duplicateGroup: {
      groupId: 'streaming',
      groupName: 'Video Streaming',
      services: ['Netflix', 'Disney+', 'HBO Max', 'Hulu'],
    },
  },
  // Duplicate - music streaming #1
  {
    id: 'sub-spotify',
    name: 'Spotify',
    category: 'Music',
    icon: '🎵',
    amount: 11.99,
    frequency: 'monthly',
    lastCharge: '2025-01-08',
    chargeCount: 12,
    status: 'active',
    transactions: [],
    priceChange: {
      previousAmount: 10.99,
      currentAmount: 11.99,
      changePercent: 9.1,
      changeDate: '2024-11-08',
    },
    priceHistory: [
      { date: '2024-01-08', amount: 10.99 },
      { date: '2024-11-08', amount: 11.99 },
    ],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation',
    duplicateGroup: {
      groupId: 'music',
      groupName: 'Music Streaming',
      services: ['Spotify', 'Apple Music'],
    },
  },
  // Duplicate - music streaming #2
  {
    id: 'sub-apple-music',
    name: 'Apple Music',
    category: 'Music',
    icon: '🍎',
    amount: 10.99,
    frequency: 'monthly',
    lastCharge: '2025-01-05',
    chargeCount: 8,
    status: 'potential-leak',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Cancel through Apple ID settings or iTunes',
    duplicateGroup: {
      groupId: 'music',
      groupName: 'Music Streaming',
      services: ['Spotify', 'Apple Music'],
    },
  },
  // Hard to cancel + potential leak
  {
    id: 'sub-adobe',
    name: 'Adobe Creative Cloud',
    category: 'Productivity',
    icon: '🎨',
    amount: 59.99,
    frequency: 'monthly',
    lastCharge: '2025-01-05',
    chargeCount: 6,
    status: 'potential-leak',
    transactions: [],
    priceChange: {
      previousAmount: 54.99,
      currentAmount: 59.99,
      changePercent: 9.1,
      changeDate: '2024-12-05',
    },
    priceHistory: [
      { date: '2024-07-05', amount: 54.99 },
      { date: '2024-12-05', amount: 59.99 },
    ],
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Phone call required, early termination fee up to 50% remaining contract',
    duplicateGroup: {
      groupId: 'streaming',
      groupName: 'Video Streaming',
      services: ['Netflix', 'Disney+', 'HBO Max', 'Hulu'],
    },
  },
  // Disney+ - part of streaming duplicates
  {
    id: 'sub-disney',
    name: 'Disney+',
    category: 'Entertainment',
    icon: '🏰',
    amount: 13.99,
    frequency: 'monthly',
    lastCharge: '2025-01-12',
    chargeCount: 4,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation',
    duplicateGroup: {
      groupId: 'streaming',
      groupName: 'Video Streaming',
      services: ['Netflix', 'Disney+', 'HBO Max', 'Hulu'],
    },
  },
  // Zombie subscription - gym not used
  {
    id: 'sub-gym',
    name: 'Planet Fitness',
    category: 'Fitness',
    icon: '💪',
    amount: 24.99,
    frequency: 'monthly',
    lastCharge: '2025-01-01',
    chargeCount: 10,
    status: 'potential-leak',
    transactions: [],
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Requires certified letter or in-person visit to cancel',
    isZombie: true,
    zombieDays: 83,
  },
  {
    id: 'sub-chatgpt',
    name: 'ChatGPT Plus',
    category: 'AI',
    icon: '🤖',
    amount: 20.00,
    frequency: 'monthly',
    lastCharge: '2025-01-03',
    chargeCount: 5,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation in settings',
  },
  // Multiple price increases
  {
    id: 'sub-hbo',
    name: 'HBO Max',
    category: 'Entertainment',
    icon: '📺',
    amount: 17.99,
    frequency: 'monthly',
    lastCharge: '2025-01-07',
    chargeCount: 14,
    status: 'active',
    transactions: [],
    priceChange: {
      previousAmount: 15.99,
      currentAmount: 17.99,
      changePercent: 12.5,
      changeDate: '2024-09-07',
    },
    priceHistory: [
      { date: '2023-09-07', amount: 14.99 },
      { date: '2024-03-07', amount: 15.99 },
      { date: '2024-09-07', amount: 17.99 },
    ],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation',
    duplicateGroup: {
      groupId: 'streaming',
      groupName: 'Video Streaming',
      services: ['Netflix', 'Disney+', 'HBO Max', 'Hulu'],
    },
  },
  // Free trial trap
  {
    id: 'sub-hulu',
    name: 'Hulu',
    category: 'Entertainment',
    icon: '📺',
    amount: 0.00,
    frequency: 'monthly',
    lastCharge: '2025-01-20',
    chargeCount: 1,
    status: 'new',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel before trial ends',
    isTrial: true,
    trialEndsAt: '2025-02-02',
    trialConvertsTo: 215.88, // $17.99/mo * 12
    duplicateGroup: {
      groupId: 'streaming',
      groupName: 'Video Streaming',
      services: ['Netflix', 'Disney+', 'HBO Max', 'Hulu'],
    },
  },
  {
    id: 'sub-nytimes',
    name: 'New York Times',
    category: 'News',
    icon: '📰',
    amount: 17.00,
    frequency: 'monthly',
    lastCharge: '2025-01-02',
    chargeCount: 3,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Must call or chat with customer service',
    priceChange: {
      previousAmount: 4.00,
      currentAmount: 17.00,
      changePercent: 325,
      changeDate: '2025-01-02',
    },
    priceHistory: [
      { date: '2024-10-02', amount: 4.00 },
      { date: '2025-01-02', amount: 17.00 },
    ],
  },
  // Micro-leaks (small charges)
  {
    id: 'sub-icloud',
    name: 'iCloud',
    category: 'Storage',
    icon: '☁️',
    amount: 2.99,
    frequency: 'monthly',
    lastCharge: '2025-01-11',
    chargeCount: 24,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Cancel through Apple ID settings',
    isMicroLeak: true,
  },
  {
    id: 'sub-google-one',
    name: 'Google One',
    category: 'Storage',
    icon: '☁️',
    amount: 1.99,
    frequency: 'monthly',
    lastCharge: '2025-01-09',
    chargeCount: 18,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click cancellation in Google settings',
    isMicroLeak: true,
    duplicateGroup: {
      groupId: 'storage',
      groupName: 'Cloud Storage',
      services: ['iCloud', 'Google One'],
    },
  },
  // Another micro-leak
  {
    id: 'sub-unknown-app',
    name: 'Unknown App',
    category: 'Other',
    icon: '❓',
    amount: 0.99,
    frequency: 'monthly',
    lastCharge: '2025-01-15',
    chargeCount: 6,
    status: 'potential-leak',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Check App Store or Google Play subscriptions',
    isMicroLeak: true,
  },
  {
    id: 'sub-nordvpn',
    name: 'NordVPN',
    category: 'Security',
    icon: '🔒',
    amount: 12.99,
    frequency: 'monthly',
    lastCharge: '2025-01-06',
    chargeCount: 2,
    status: 'new',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Contact support or use account settings',
  },
  // Zombie - Peloton unused
  {
    id: 'sub-peloton',
    name: 'Peloton',
    category: 'Fitness',
    icon: '🚴',
    amount: 44.00,
    frequency: 'monthly',
    lastCharge: '2025-01-04',
    chargeCount: 8,
    status: 'potential-leak',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Cancel in account settings or contact support',
    isZombie: true,
    zombieDays: 62,
  },
  // Food delivery duplicates
  {
    id: 'sub-dashpass',
    name: 'DashPass',
    category: 'Food',
    icon: '🍕',
    amount: 9.99,
    frequency: 'monthly',
    lastCharge: '2025-01-08',
    chargeCount: 6,
    status: 'active',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-click in DoorDash app',
    duplicateGroup: {
      groupId: 'food-delivery',
      groupName: 'Food Delivery',
      services: ['DashPass', 'Uber One'],
    },
  },
  {
    id: 'sub-uber-one',
    name: 'Uber One',
    category: 'Food',
    icon: '🚗',
    amount: 9.99,
    frequency: 'monthly',
    lastCharge: '2025-01-10',
    chargeCount: 4,
    status: 'potential-leak',
    transactions: [],
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel in Uber app settings',
    duplicateGroup: {
      groupId: 'food-delivery',
      groupName: 'Food Delivery',
      services: ['DashPass', 'Uber One'],
    },
  },
  // Another trial
  {
    id: 'sub-audible',
    name: 'Audible',
    category: 'Reading',
    icon: '🎧',
    amount: 0.00,
    frequency: 'monthly',
    lastCharge: '2025-01-25',
    chargeCount: 1,
    status: 'new',
    transactions: [],
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Cancel through Amazon account',
    isTrial: true,
    trialEndsAt: '2025-01-30',
    trialConvertsTo: 179.40, // $14.95/mo * 12
  },
];
